from azure.ai.inference import ChatCompletionsClient
from azure.ai.inference.models import SystemMessage, UserMessage
from azure.core.credentials import AzureKeyCredential
import os, json, asyncio

EVALUATOR_SYSTEM_PROMPT = """You are a strict, independent AI evaluation judge.
You will receive a user question, the dataset summary, and an answer generated by GPT-4o.
Evaluate the answer and return ONLY a valid JSON object. No text before or after the JSON.

Return exactly this structure:
{
  "evaluator_model": "Phi-4-mini-reasoning",
  "correctness": {
    "score": <integer 1 to 10>,
    "reason": "<one sentence>"
  },
  "quality": {
    "score": <integer 1 to 10>,
    "reason": "<one sentence>"
  },
  "hallucination": {
    "risk": "<LOW or MEDIUM or HIGH>",
    "detected": <true or false>,
    "reason": "<one sentence>"
  },
  "overall_verdict": "<PASS or REVIEW or FAIL>",
  "summary": "<two sentences summarizing your evaluation>"
}

Scoring rules:
- correctness: Does the answer match facts in the dataset summary?
- quality: Is it clear, insightful, structured, and useful?
- hallucination: Did GPT-4o invent columns, numbers, or facts not in the data?
- PASS   = correctness >= 7 AND hallucination not detected
- REVIEW = correctness 4 to 6 OR minor concerns
- FAIL   = correctness < 4 OR hallucination detected"""


async def evaluate_response(
    question: str,
    ai_answer: str,
    data_summary: dict
) -> dict:

    # Client created here — reads .env values fresh every call
    endpoint   = os.getenv("AZURE_PHI_ENDPOINT")
    key        = os.getenv("AZURE_PHI_KEY")
    deployment = os.getenv("AZURE_PHI_DEPLOYMENT", "Phi-4-mini-reasoning")

    print(f"[EVALUATOR] endpoint   = {endpoint}")
    print(f"[EVALUATOR] deployment = {deployment}")
    print(f"[EVALUATOR] key        = {key[:8]}..." if key else "[EVALUATOR] key = MISSING")

    phi_client = ChatCompletionsClient(
        endpoint=endpoint,
        credential=AzureKeyCredential(key)
    )

    user_content = f"""QUESTION ASKED BY USER:
{question}

DATASET SUMMARY (ground truth):
{json.dumps(data_summary, indent=2, default=str)}

GPT-4o ANSWER TO EVALUATE:
{ai_answer}

Now evaluate the above answer and return only the JSON object."""

    def call_phi():
        response = phi_client.complete(
            model=deployment,
            messages=[
                SystemMessage(content=EVALUATOR_SYSTEM_PROMPT),
                UserMessage(content=user_content)
            ],
            max_tokens=500,
            temperature=0.1
        )
        return response.choices[0].message.content

    loop = asyncio.get_event_loop()
    raw  = await loop.run_in_executor(None, call_phi)

    print(f"[EVALUATOR] raw response = {raw[:300]}")

    extracted = extract_json(raw)

    try:
        return json.loads(extracted)
    except json.JSONDecodeError:
        return {
            "evaluator_model": "Phi-4-mini-reasoning",
            "correctness":   {"score": 0, "reason": "Could not parse evaluator response"},
            "quality":       {"score": 0, "reason": "Could not parse evaluator response"},
            "hallucination": {"risk": "UNKNOWN", "detected": False, "reason": "Parse failed"},
            "overall_verdict": "REVIEW",
            "summary": f"Phi-4 evaluation could not be parsed. Raw: {raw[:300]}"
        }


def extract_json(text: str) -> str:
    """
    Phi-4-mini-reasoning thinks out loud before outputting JSON.
    This strips the reasoning and returns only the JSON block.
    """
    # Case 1: ```json ... ``` fences
    if "```json" in text:
        try:
            return text.split("```json")[1].split("```")[0].strip()
        except IndexError:
            pass

    # Case 2: ``` ... ``` without language label
    if "```" in text:
        parts = text.split("```")
        for part in parts:
            part = part.strip()
            if part.startswith("{"):
                return part

    # Case 3: find the JSON object inside reasoning text
    start = text.find("{")
    end   = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        return text[start:end + 1]

    return text.strip()